### ISSUE TITLE
mdoc-7 is missing from "/man/" folder

### ISSUE THREAD

**Issue by celtic-coder** [anaseto/gofrundis#1]
Hi Yan(@anaseto),

In the HISTORY section of the [FRUNDIS_SYNTAX(5)](https://frundis.tuxfamily.org/man/frundis_syntax-5.html) page, it refers to the **mdoc(7)** language as inspiration for some of the macro names.

However, this link is broken. The file **mdoc-7.html** file is missing from the **/man/** folder.

Only these files are in the "[/man/](https://frundis.tuxfamily.org/man/)"folder:

* [frundis-1.html](https://frundis.tuxfamily.org/man/frundis-1.html)
* [frundis_syntax-5.html](https://frundis.tuxfamily.org/man/frundis_syntax-5.html)

I presume that the missing file is similar to https://manned.org/mdoc.7 ?

Kind Regards,
Liam

**Comment by anaseto** [comment]
Hi ! Yes, thanks for pointing this out. I added a link to mdoc [manual page](https://mandoc.bsd.lv/man/mdoc.7.html), which is similar to the one you provide (the version that comes with the mandoc tools).

**Comment by celtic-coder** [comment]
Hi Yan(@anaseto),

The link that you have [given](https://mandoc.bsd.lv/man/mdoc.7.html) looks to be much more comprehensive than the one that I found and therefore more helpful.

Thanks for the quick response! 

Kind Regards,
Liam
