### ISSUE TITLE
html_coloration and other Perl scripts

### ISSUE THREAD

**Issue by celtic-coder** [anaseto/gofrundis#2]
Hi Yan (@anaseto),

On the main [Frundis web page](https://frundis.tuxfamily.org/) is an example of colorizing the Frundis code using a Perl script (html_coloration.pl):

![html_coloration-perl-script](https://user-images.githubusercontent.com/11787866/156645708-90c8f1dc-9f92-4cea-a1d0-c42a3c0b765b.png)

I realize that you have not been developing the Perl version of Frundis since 2016, but might it be useful to include some Perl scripts that were part of the ["tools" folder on CPAN](https://metacpan.org/release/ANASETO/Text-Frundis-2.16/source/tools) in the current Go repo?

For example:

* [html_coloration.pl](https://metacpan.org/release/ANASETO/Text-Frundis-2.16/source/tools/html_coloration.pl)
* [html_to_frundis.pl](https://metacpan.org/release/ANASETO/Text-Frundis-2.16/source/tools/html_to_frundis.pl)
* [latex_to_frundis.pl](https://metacpan.org/release/ANASETO/Text-Frundis-2.16/source/tools/latex_to_frundis.pl)
* [markdown_to_frundis.pl](https://metacpan.org/release/ANASETO/Text-Frundis-2.16/source/tools/markdown_to_frundis.pl)

I have an amount of my own material in the form of HTML, and it would help to see how it might appear in the form of a Frundis file. The same is true for material originally written in Markdown. These Perl scripts would aid in that transition.

The syntax highlighting (colorizing) done on the Frundis web page is useful in learning the syntax. Since I am only beginning to learn this new markup, every assistance is appreciated!

If you do not want to include the Perl scripts in the repo, that is fine. However, a link to the "html_coloration" script might be helpful to anyone curious about its operation.

Kind Regards,
Liam

**Comment by anaseto** [comment]
Hi Liam!

I've added the html_coloration.pl script used by the website in
the repos, in a misc folder. It has some improvements over the
original.

With respect to the old conversion scripts in the old Perl version
of Frundis, I just added a link in misc/README.md, as they have
not been updated since then: they're just ad hoc scripts I used at
the time to facilitate the conversion to frundis from texts I
wrote in other formats, but they are far from complete and may not
be usable as-is (though they might still be useful).

**Comment by celtic-coder** [comment]
Hi Yan (@anaseto),

Thank you for implementing commit [81e28a1](https://github.com/anaseto/gofrundis/commit/81e28a10b1d2b0d3be7ed33c9028e77343fde3f7) (add a misc folder with the html_coloration.pl script).

My Perl is fairly rusty, but the updated script will be a good foundation for any changes that might be required. Thanks again for the new version!

Kind Regards,
Liam
