### ISSUE TITLE
Meaning of "display block" and other questions

### ISSUE THREAD

**Issue by celtic-coder** [anaseto/gofrundis#3]
Hi Yan (@anaseto),

Over the years, I have used different forms of markup including [txt2tags](https://txt2tags.org/), [reStructuredText](https://www.sphinx-doc.org/en/master/usage/restructuredtext/index.html), and [AsciiDoctor](https://asciidoctor.org/). I am therefore familiar with most of the types of content that can be generated from these kinds of markup.

I looked into Groff earlier last year, but never got into it. However, it seems the terminology used in *Frundis* is based on a background of Groff / Man pages. Therefore, some terminology is unfamiliar to me.

One of those unfamiliar terms is **display block**.

In issue #1, you linked to the mandoc [mdoc.7](https://mandoc.bsd.lv/man/mdoc.7.html) man page. The [Displays and lists](https://mandoc.bsd.lv/man/mdoc.7.html#Displays_and_lists) section from the *mdoc.7* man page is the following:

![display-and-list-mdoc-7](https://user-images.githubusercontent.com/11787866/159072896-cb0b360e-e23c-47e3-9527-65422bcb28a1.png)

This is like [Displays and lists](https://frundis.tuxfamily.org/man/frundis_syntax-5.html#Displays_and_lists) section in the *FRUNDIS_SYNTAX(5)* page:

![display-and-list-frundis](https://user-images.githubusercontent.com/11787866/159074982-4e8af29b-09d4-45f7-9a0d-22485ba40b01.png)

In the *mdoc.7* man page, the definition of "Bd" is as follows:

*Begin a display block. Display blocks are used to select a different indentation and justification than the one used by the surrounding text. They may contain both macro lines and text lines. By default, a display block is preceded by a vertical space.*

I realize that **mdoc** is for formatting of manual pages and therefore this definition of *display block* is specific for this purpose. However, I am curious what is the applicable definition for *Frundis*?

Is there something that might need to be added to the **FRUNDIS_SYNTAX(5)** page to explain the purpose of *display block* and why, for example, it might be different from the **mdoc** usage?

Again, this is just for information only. I am learning about the *Frundis* application and any help with further understanding would be appreciated!

Kind Regards,
Liam

**Comment by anaseto** [comment]
Hi !

Actually, Bd in frundis is a very generic kind of macro for
defining styled blocks of any kind (think HTML container or LaTeX
container-kind environment). The actual rendering for a specific
output format will depend on a dtag definition with the X macro
that configures rendering. By default, if no dtags are defined, it
serves almost the same purpose as a “div” element in html with no
special styling (a simple container).

I've made a commit which explains this in the man page a bit more
clearly.

Yon

**Comment by celtic-coder** [comment]
Hi Yan (@anaseto),

Thank you for the clarification and for implementing commit [a9cc2f8]( https://github.com/anaseto/gofrundis/commit/a9cc2f8f58911357e9b39a1c77c9f3669267d5a7). I see that [/doc/frundis_syntax.5](https://github.com/anaseto/gofrundis/blob/a9cc2f8f58911357e9b39a1c77c9f3669267d5a7/doc/frundis_syntax.5) in the repo has been updated. However, it seems the corresponding page on the website [(frundis_syntax-5.html#Bd)](https://frundis.tuxfamily.org/man/frundis_syntax-5.html#Bd) has not been updated yet?

By the way, since I am only beginning my journey of learning about "man" pages, how do you generate the [frundis.1](https://github.com/anaseto/gofrundis/blob/master/doc/frundis.1) and [frundis_syntax.5](https://github.com/anaseto/gofrundis/blob/master/doc/frundis_syntax.5) files in the "doc" folder in the repo? Is this done with the "mandoc" utility?

Kind Regards,
Liam

**Comment by anaseto** [comment]
Hi Liam,                                                                                                                                     
                                                                                                                                          
I've updated the man page on the website too now. 
                                                                                                                          
The files frundis.1 and frundis_syntax.5 are written by hand using                                                                                 
the mdoc language (which provides many macros with specialized                                                                                     
semantics for manual pages, for example for command options and                                                                                    
arguments, manual page date, etc.), and then formatted man pages                                                                                   
(for example on the website) are generatted by the mandoc utility,                                                                                 
yes.

**Comment by celtic-coder** [comment]
Hi Yan (@anaseto),

Thanks again for the clarification. I can now see another parallel between *MDoc* and the *Frundis* applications. Since your response 10 days ago, I have done some further research resulting in several observations and questions.

### Creating "man" pages

After I had asked about how the *frundis.1* and *frundis_syntax.5* pages were created, I came across the [Practical UNIX Manpages](http://manpages.bsd.lv/index.html) (or "Practical UNIX Manuals:mdoc"), which links to [a great tutorial](http://manpages.bsd.lv/mdoc.html) on the practical steps to create a "man" page from scratch. This tutorial has clarified several thoughts in my mind and has shown the work required to create those two *Frundis* man pages.

### Background in using RUNOFF

Further down the main page is a link to [The History of UNIX Manpages](http://manpages.bsd.lv/history.html), which reminded me that back in the mid 80s, I worked for a company where I used RUNOFF on a DEC VAX minicomputer using the [DEC VAX DIGITAL Standard Runoff Reference Manual](https://archive.org/details/h42_DEC_VAX_DIGITAL_Standard_Runoff_Reference_Manual/page/n244/mode/1up) to create those documents.

Unfortunately, I didn't use RUNOFF or the subsequent *roff*, *troff* and *groff* applications in any serious way since. Therefore, *Frundis* is the first modern typesetting application, in that lineage, that I'm using to produce documents. I am looking forward to investigating further.

### Semantic Markup - MDoc and Frundis

*MDOC(7)* gives the following for the NAME:

> mdoc - semantic markup language for formatting manual pages

Similarly, *frundis_syntax.5* has the following:

>semantic markup language for formatting documents

As a generalization, would it be correct to state that *Frundis* is a specialized subset of *Mdoc* for the creation of several outputs, just like *Mdoc* is a specialized subset of *Roff* for the creation of one output? 

If so, would it be helpful to have some background in *Mdoc* or *Roff* before using *Frundis* or is it expected that *Frundis* can be used independently?

From reading the PDF of [mandoc - 
from scratch to the standard BSD documentation toolkit in 6 years (2015)](http://www.openbsd.org/papers/nycbug15-mandoc.pdf) (p.10), it would appear that one of the advantages of **semantic markup** is to enable a markup-sensitive search. However, is this advantage only found on Linux / BSD platforms? 

How does *semantic markup* carry over to the *Frundis* application? Are there other advantages of semantic markup, for example? Are these found in all the available outputs? Might these also carry over to the Windows platform that I use?

### Display Blocks code: Footnotes and Include files

From the [testdata/data/display_blocks.frundis](https://github.com/anaseto/gofrundis/blob/master/testdata/data/display_blocks.frundis) page on GitHub, I can see the different demonstrated examples, which are helpful. They give an indication of what can be achieved. A question: might there a way of creating footnotes? If so, is the "Mom" output the only one that could be used for [footnotes](https://www.schaffter.ca/mom/momdoc/docelement.html#footnote-intro)?

The [display_blocks.frundis](https://github.com/anaseto/gofrundis/blob/a9cc2f8f58911357e9b39a1c77c9f3669267d5a7/testdata/data/display_blocks.frundis#L17) file at line 17, has an "include file" for `code.frundis`:

`.If code.frundis`

How does it know where to find this file? Is this because the FRUNDISLIB is defined in the [testdata/testgofrundis.go](https://github.com/anaseto/gofrundis/blob/a9cc2f8f58911357e9b39a1c77c9f3669267d5a7/testdata/testgofrundis.go#L22) as:

`err = os.Setenv("FRUNDISLIB", "data/includes")`

### Final Thoughts

Having worked extensively with different forms of markup in the past, I am interested in seeing how this **semantic markup language for formatting documents** can be used in my own personal projects. It would be helpful to see what are the possible advantages to this markup. 

I have put many hours of work into LaTeX documents, for example, but it can be frustrating when trying to deal with an obscure problem. I am interested in *Groff* and have huge admiration for Peter Schaffter's *Mom* macros. His [HTML documentation](https://www.schaffter.ca/mom/momdoc/toc.html), is a monumental work, one of the best kinds of application or software technical documentation that I have ever come across. It is only surpassed by the detail in the [om.tmac](https://github.com/gnu-mirror-unofficial/groff/blob/master/contrib/mom/om.tmac) typesetting/document-processing macro set.

Given that *Frundis* has been in production since 2015, it produces the types of output I have used in the past, is built on technology that is almost 60 years old -- it therefore has all the hallmarks of an application in which I would like to invest further time and effort. However, I would like to get a better understanding of its typesetting capabilities, given its marvellous heritage, before doing so.

Kind Regards,
Liam

**Comment by anaseto** [comment]
Hi Liam,

> If so, would it be helpful to have some background in Mdoc or Roff before using Frundis or is it expected that Frundis can be used independently?

It can be used independently. Actually, when using Frundis, it's only needed to have some minimal background of the *target* language(s) you want to export to : when using the `X` macro to give meaning to semantical tags, you can control how it will be rendered (element name and attributes for HTML controlled then by css, or command name for LaTeX, or macro name for Mom).

Even though Frundis shares with mdoc and roff the syntax (with some old archaisms removed), Frundis is a quite generic semantic markup language that allows quite easily to have a common source code that can be exported to other languages with enough control over the final styling. So Frundis is not the subset of a particular language, though of course a specific output is limited by the target language. Frundis did target originally mainly HTML and LaTeX, with Mom output being added later. Frundis is more like a roff-style cousin of XML, but much simpler (built-in simple extensibility with no complex and slow external XSLT processing, which 90% of the time would be overkill) and a much friendler roff syntax.

> How does semantic markup carry over to the Frundis application? Are there other advantages of semantic markup, for example? Are these found in all the available outputs? Might these also carry over to the Windows platform that I use?

It can be useful on any platform. Semantic markup has many advantages, but the main one is easier maintenance of documents, allowing to easily tweak style accross one document (or several documents) without requiring error-prone and time-consuming changes all over the place. In HTML, you do semantic markup using for example class attributes, while in LaTeX you do that by defining your own commands : Frundis provides a common abstraction.

A year ago, I gave [on this reddit thread](https://www.reddit.com/r/ProgrammingLanguages/comments/n9yxq0/on_semantic_markup_language_design_and_how_i/) a summary of the rationales for the Frundis language design among markup languages, it may help you understand better the design and goals. This is the only summary I've given in english about Frundis' design that's more detailed than the faq on the website. I also answered there some questions.

> A question: might there a way of creating [footnotes](https://www.schaffter.ca/mom/momdoc/docelement.html#footnote-intro)? If so, is the "Mom" output the only one that could be used for footnotes?

It's possible as long as it is in the target format : if you define a footnote tag using the X command for each target language (for example `.X mtag -f latex -t footnote -c footnote` does it for LaTeX), then you can create footnotes using `Sm` and `Bm` with the `-ns -t footnote` option, and even define a shorthand macro for this. Sometimes, just defining a tag may not be enough, and then you can define a wrapper macro around some raw target code (using format blocks), providing different rendering for each output format you need (passing distinct arguments to the `-f` option).

> I have put many hours of work into LaTeX documents, for example, but it can be frustrating when trying to deal with an obscure problem.

Frundis is actually quite good at being a better syntax to produce LaTeX documents (for example I used Frundis for a PhD thesis, exported then to LaTeX) while avoiding obscure syntax errors, and using raw LaTeX only for very specific things (like mathematical formulas).

**Comment by celtic-coder** [comment]
Hi Yan (@anaseto),

Thank you for a clear explanation of the philosophy and the practical application of _Frundis_. I had come across the Reddit thread previously but now that I've had some experience researching and using Frundis, I can better understand what you were saying.

My apologies for leaving this issue open. My wife and I are selling our home and moving house. I will close this issue and come back with any further questions when we are finally settled in our new location.

Thanks again for your comprehensive reply!

Kind Regards,
Liam

**Comment by anaseto** [comment]
Hi Liam,

I've updated the man page on the website too now.

The files frundis.1 and frundis_syntax.5 are written by hand using
the mdoc language (which provides many macros with specialized
semantics for manual pages, for example for command options and
arguments, manual page date, etc.), and then formatted man pages
(for example on the website) are generatted by the mandoc utility,
yes.

Yon

EDIT: this is a replicate from an email from March, I have no idea why it appeared here again, probably a github bug or some kind of spam.

**Comment by celtic-coder** [comment]
Hi Yon (@anaseto),

First, apologies for getting your first name incorrect! 😢 (For my own peace of mind, I confirmed the details [here](https://projects.tuxfamily.org/?do=tags;search=subject::text%20processing#%3Fdo%3Duser%3Bname%3Danaseto)).

Second, thanks for updating the website. Completing the manual pages by hand is a huge amount of work, but I guess that once the main portion is done, then minor modifications are relatively easy.

Again, apologies for getting your first name wrong!

Kind Regards,
Liam

**Comment by anaseto** [comment]
Hi Liam,

Haha, no worries, I lived in brittany for a while, and people there called me Yann quite often at first :-) Hope you're doing well in your new location!

BTW, I don't know why three days ago and old email reply of mine from march appeared again on this thread here, it seems that github had some kind of bug, because I checked my email server logs, and there was nothing there.
